-- Update supplier passwords to "1234"
-- Run this SQL in phpMyAdmin or MySQL

-- First, generate the password hash (run this in PHP or use the update script)
-- The hash for "1234" will be generated by PHP's password_hash() function

-- To update manually, you can use this SQL after generating the hash:
-- Replace YOUR_HASH_HERE with the actual hash from the PHP script

UPDATE suppliers 
SET password = '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi' 
WHERE id IN (1, 2, 3);

-- Note: The hash above is a placeholder. 
-- Use the update_supplier_passwords.php script to generate the correct hash.

